### ISSUE TITLE
Depenedency list for this project?

### ISSUE THREAD

**Issue by Rajat-Mehta** [darylclimb/cvml_project#1]
Could you please mention the list of dependencies for lidar_camera_projection project. I cloned your repo but am not able to run it. Getting missing packages errors.

For eg.: 

```
  % get_backend())
Traceback (most recent call last):
  File "lidar_camera_project.py", line 111, in <module>
    render_lidar_with_boxes(pc_velo, labels, calib, img_width=img_width, img_height=img_height)
  File "lidar_camera_project.py", line 42, in render_lidar_with_boxes
    fgcolor=None, engine=None, size=(1000, 500))
  File "/home/rajat/.local/lib/python3.5/site-packages/mayavi/tools/figure.py", line 63, in figure
    engine = get_engine()
  File "/home/rajat/.local/lib/python3.5/site-packages/mayavi/tools/engine_manager.py", line 101, in get_engine
    return self.new_engine()
  File "/home/rajat/.local/lib/python3.5/site-packages/mayavi/tools/engine_manager.py", line 146, in new_engine
    check_backend()
  File "/home/rajat/.local/lib/python3.5/site-packages/mayavi/tools/engine_manager.py", line 49, in check_backend
    ''')
ImportError: Could not import backend for traits
_______________________________________________________________________________
Make sure that you have either the TraitsBackendWx or the TraitsBackendQt
projects installed. If you installed Mayavi with easy_install, try
easy_install <pkg_name>. easy_install Mayavi[app] will also work.

If you performed a source checkout, be sure to run 'python setup.py install'
in Traits, TraitsGUI, and the Traits backend of your choice.

Also make sure that either wxPython or PyQT is installed.
wxPython: http://www.wxpython.org/
PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro
```

**Comment by darylclimb** [comment]
Hi @Rajat-Mehta 

I would recommend installing inside a conda env. I have added a requirement.txt.
